/**********************************************************************
 * Changelog
 * All notable changes to this project will be documented in this file.
 **********************************************************************
 * Author            : Deshmukh P
 *
 * Date created      : 08/12/2024
 *
 * Purpose			 : Define Constant
 *********************************************************************
 */
// ERROR MESSAGE CONSTANTS
const ERROR_MESSAGE = {
  INTERNAL_SERVER_ERROR: 'INTERNAL SERVER ERROR',
  METHOD_NOT_ALLOWED: 'METHOD NOT ALLOWED',
  UNAUTHORIZED: 'UNAUTHORIZED ACCESS DETECTED',
  BAD_REQUEST: 'BAD REQUEST',
  KEY_DUPLICATION: 'EMAIL ALREADY EXISTS',
  REQUIRED_PARAMETERS_MISSING: 'REQUIRED PARAMETERS MISSING',
  MISSING_ACCESS_TOKEN: 'ACCESS TOKEN REQUIRED IN AUTHORIZATION HEADER',
  INVALID_ACCESS_TOKEN: 'INVALID ACCESS TOKEN SUPPLIED IN AUTHORIZATION HEADER',
  EXPIRED_ACCESS_TOKEN: 'EXPIRED ACCESS TOKEN SUPPLIED IN AUTHORIZATION HEADER',
  FILE_SYSTEM: 'ERROR IN FILE SYSTEM DELETION',
  MISSING_ADMIN_PK: 'ACCESS TOKEN REQUIRED IN AUTHORIZATION HEADER',
  INVALID_ADMIN_PK:
    'INVALID ADMIN PRIVATE KEY SUPPLIED IN AUTHORIZATION HEADER',
  NO_ROUTE_FOUND: 'ROUTE NOT FOUND',
  CHANGE_BROWSER: 'PLEASE MAKE SURE YOU USE THE SAME BROWSER',
};

// HTTP STATUS CODES
const HTTP_STATUS_CODE = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOW: 405,
  CONFLICT: 409,
  EXPIRED_ACCESS_TOKEN: 410,
  INTERNAL_SERVER: 500,
};

const CART_ITEM_STATUS = {
  Processing: 'Processing',
  Shipped: 'Shipped',
  Delivered: 'Delivered',
  Cancelled: 'Cancelled',
  Not_processed: 'Not processed',
};

// EXPORT MODULE
export { ERROR_MESSAGE, HTTP_STATUS_CODE, CART_ITEM_STATUS };
